# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastrar(object):
    def setupUi(self, Cadastrar):
        Cadastrar.setObjectName("Cadastrar")
        Cadastrar.resize(460, 418)
        Cadastrar.setStyleSheet("QWidget#titulo {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QLabel#lbl_titulo {\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLabel, QLineEdit, QPushButton {\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton#btn_salvar {    \n"
"    background-color: rgb(0, 170, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton#btn_fechar {    \n"
"    background-color: rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Cadastrar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo = QtWidgets.QWidget(Cadastrar)
        self.titulo.setMinimumSize(QtCore.QSize(0, 50))
        self.titulo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.titulo.setObjectName("titulo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.titulo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_titulo = QtWidgets.QLabel(self.titulo)
        self.lbl_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.verticalLayout_4.addWidget(self.lbl_titulo)
        self.verticalLayout.addWidget(self.titulo)
        self.componentes = QtWidgets.QWidget(Cadastrar)
        self.componentes.setObjectName("componentes")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.componentes)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_mensagem = QtWidgets.QLabel(self.componentes)
        self.lbl_mensagem.setStyleSheet("color: green;")
        self.lbl_mensagem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mensagem.setObjectName("lbl_mensagem")
        self.verticalLayout_2.addWidget(self.lbl_mensagem)
        self.label = QtWidgets.QLabel(self.componentes)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.edt_nome = QtWidgets.QLineEdit(self.componentes)
        self.edt_nome.setMinimumSize(QtCore.QSize(0, 30))
        self.edt_nome.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edt_nome.setObjectName("edt_nome")
        self.verticalLayout_2.addWidget(self.edt_nome)
        self.label_4 = QtWidgets.QLabel(self.componentes)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.cmb_sexo = QtWidgets.QComboBox(self.componentes)
        self.cmb_sexo.setMinimumSize(QtCore.QSize(0, 30))
        self.cmb_sexo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cmb_sexo.setObjectName("cmb_sexo")
        self.cmb_sexo.addItem("")
        self.cmb_sexo.addItem("")
        self.verticalLayout_2.addWidget(self.cmb_sexo)
        self.label_2 = QtWidgets.QLabel(self.componentes)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.edt_salario = QtWidgets.QLineEdit(self.componentes)
        self.edt_salario.setMinimumSize(QtCore.QSize(0, 30))
        self.edt_salario.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edt_salario.setObjectName("edt_salario")
        self.verticalLayout_2.addWidget(self.edt_salario)
        self.label_3 = QtWidgets.QLabel(self.componentes)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.edt_departamento = QtWidgets.QLineEdit(self.componentes)
        self.edt_departamento.setMinimumSize(QtCore.QSize(0, 30))
        self.edt_departamento.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edt_departamento.setObjectName("edt_departamento")
        self.verticalLayout_2.addWidget(self.edt_departamento)
        self.verticalLayout.addWidget(self.componentes)
        self.botoes = QtWidgets.QWidget(Cadastrar)
        self.botoes.setObjectName("botoes")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.botoes)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_fechar = QtWidgets.QPushButton(self.botoes)
        self.btn_fechar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_fechar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_fechar.setObjectName("btn_fechar")
        self.horizontalLayout_2.addWidget(self.btn_fechar)
        self.btn_salvar = QtWidgets.QPushButton(self.botoes)
        self.btn_salvar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_salvar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_salvar.setObjectName("btn_salvar")
        self.horizontalLayout_2.addWidget(self.btn_salvar)
        self.verticalLayout.addWidget(self.botoes)

        self.retranslateUi(Cadastrar)
        QtCore.QMetaObject.connectSlotsByName(Cadastrar)

    def retranslateUi(self, Cadastrar):
        _translate = QtCore.QCoreApplication.translate
        Cadastrar.setWindowTitle(_translate("Cadastrar", "Dialog"))
        self.lbl_titulo.setText(_translate("Cadastrar", "CADASTRO FUNCIONÁRIOS"))
        self.lbl_mensagem.setText(_translate("Cadastrar", "TextLabel"))
        self.label.setText(_translate("Cadastrar", "Nome"))
        self.label_4.setText(_translate("Cadastrar", "Sexo"))
        self.cmb_sexo.setItemText(0, _translate("Cadastrar", "Masculino"))
        self.cmb_sexo.setItemText(1, _translate("Cadastrar", "Feminino"))
        self.label_2.setText(_translate("Cadastrar", "Salário"))
        self.label_3.setText(_translate("Cadastrar", "Departamento"))
        self.btn_fechar.setText(_translate("Cadastrar", "Fechar"))
        self.btn_salvar.setText(_translate("Cadastrar", "Salvar"))
