# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(430, 491)
        Main.setStyleSheet("QWidget#titulo {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QLabel#lbl_titulo {\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLabel, QLineEdit, QPushButton {\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton#btn_salvar {    \n"
"    background-color: rgb(0, 170, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton#btn_fechar {    \n"
"    background-color: rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}\n"
"")
        self.painel_principal = QtWidgets.QWidget(Main)
        self.painel_principal.setObjectName("painel_principal")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.painel_principal)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titulo = QtWidgets.QWidget(self.painel_principal)
        self.titulo.setMinimumSize(QtCore.QSize(0, 50))
        self.titulo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.titulo.setObjectName("titulo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.titulo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_titulo = QtWidgets.QLabel(self.titulo)
        self.lbl_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.verticalLayout_4.addWidget(self.lbl_titulo)
        self.verticalLayout_3.addWidget(self.titulo)
        self.componentes = QtWidgets.QWidget(self.painel_principal)
        self.componentes.setObjectName("componentes")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.componentes)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_mensagem = QtWidgets.QLabel(self.componentes)
        self.lbl_mensagem.setStyleSheet("color: green;")
        self.lbl_mensagem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mensagem.setObjectName("lbl_mensagem")
        self.verticalLayout_2.addWidget(self.lbl_mensagem)
        self.label = QtWidgets.QLabel(self.componentes)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.edt_nome = QtWidgets.QLineEdit(self.componentes)
        self.edt_nome.setMinimumSize(QtCore.QSize(0, 30))
        self.edt_nome.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edt_nome.setObjectName("edt_nome")
        self.verticalLayout_2.addWidget(self.edt_nome)
        self.label_4 = QtWidgets.QLabel(self.componentes)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.cmb_sexo = QtWidgets.QComboBox(self.componentes)
        self.cmb_sexo.setMinimumSize(QtCore.QSize(0, 30))
        self.cmb_sexo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cmb_sexo.setObjectName("cmb_sexo")
        self.cmb_sexo.addItem("")
        self.cmb_sexo.addItem("")
        self.verticalLayout_2.addWidget(self.cmb_sexo)
        self.label_2 = QtWidgets.QLabel(self.componentes)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.edt_salario = QtWidgets.QLineEdit(self.componentes)
        self.edt_salario.setMinimumSize(QtCore.QSize(0, 30))
        self.edt_salario.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edt_salario.setObjectName("edt_salario")
        self.verticalLayout_2.addWidget(self.edt_salario)
        self.label_3 = QtWidgets.QLabel(self.componentes)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.edt_departamento = QtWidgets.QLineEdit(self.componentes)
        self.edt_departamento.setMinimumSize(QtCore.QSize(0, 30))
        self.edt_departamento.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edt_departamento.setObjectName("edt_departamento")
        self.verticalLayout_2.addWidget(self.edt_departamento)
        self.verticalLayout_3.addWidget(self.componentes)
        self.botoes = QtWidgets.QWidget(self.painel_principal)
        self.botoes.setObjectName("botoes")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.botoes)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_fechar = QtWidgets.QPushButton(self.botoes)
        self.btn_fechar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_fechar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_fechar.setObjectName("btn_fechar")
        self.horizontalLayout_2.addWidget(self.btn_fechar)
        self.btn_salvar = QtWidgets.QPushButton(self.botoes)
        self.btn_salvar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_salvar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_salvar.setObjectName("btn_salvar")
        self.horizontalLayout_2.addWidget(self.btn_salvar)
        self.verticalLayout_3.addWidget(self.botoes)
        self.tbl_funcionarios = QtWidgets.QTableWidget(self.painel_principal)
        self.tbl_funcionarios.setObjectName("tbl_funcionarios")
        self.tbl_funcionarios.setColumnCount(4)
        self.tbl_funcionarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_funcionarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_funcionarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_funcionarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_funcionarios.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.tbl_funcionarios)
        Main.setCentralWidget(self.painel_principal)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.lbl_titulo.setText(_translate("Main", "CADASTRO E LISTAGEM DE FUNCIONÁRIOS"))
        self.lbl_mensagem.setText(_translate("Main", "TextLabel"))
        self.label.setText(_translate("Main", "Nome"))
        self.label_4.setText(_translate("Main", "Sexo"))
        self.cmb_sexo.setItemText(0, _translate("Main", "Masculino"))
        self.cmb_sexo.setItemText(1, _translate("Main", "Feminino"))
        self.label_2.setText(_translate("Main", "Salário"))
        self.label_3.setText(_translate("Main", "Departamento"))
        self.btn_fechar.setText(_translate("Main", "Fechar"))
        self.btn_salvar.setText(_translate("Main", "Salvar"))
        item = self.tbl_funcionarios.horizontalHeaderItem(0)
        item.setText(_translate("Main", "Nome"))
        item = self.tbl_funcionarios.horizontalHeaderItem(1)
        item.setText(_translate("Main", "Sexo"))
        item = self.tbl_funcionarios.horizontalHeaderItem(2)
        item.setText(_translate("Main", "Salário"))
        item = self.tbl_funcionarios.horizontalHeaderItem(3)
        item.setText(_translate("Main", "Departamento"))
